version: '3.8'
services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '127.0.0.1:${DB_PORT:-3033}:3306'
    volumes:
      - ./db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "127.0.0.1:8082:8080"
